[package]
name = "rsamplr"
version = "0.3.1"
edition = "2024"
license = "AGPL-3.0-only"
publish = false
rust-version = "1.85.1"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
num-traits = "0.2.19"
savvy = "0.9.4"
# envisim_estimate = {version="0.6.0"}
# envisim_samplr = {version="0.7.0"}
# envisim_utils = {version="0.6.0", default-features=false}
envisim_estimate = {version="*", path="../../../envisim_estimate"}
envisim_samplr = {version="*", path="../../../envisim_samplr"}
envisim_utils = {version="*", path="../../../envisim_utils", default-features=false}

[lints]
workspace = true

[profile.release]
# By default, on release build, savvy terminates the R session when a panic
# occurs. This is the right behavior in that a panic means such a fatal event
# where we can have no hope of recovery.
#
# cf. https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html
#
# However, it's possible that the panic is thrown by some of the dependency
# crate and there's little you can do. In such cases, you can change the
# following line to `panic = "unwind"` to always catch a panic.
panic = "abort"
