rust_src := 'src/rust'
manifest := rust_src + '/Cargo.toml'
cargo_lock := rust_src + '/Cargo.lock'
r_source := 'R/*'
rust_source := rust_src + '/src/**/*.rs'

# Default to just --list
default:
  @just --list

# Clean the environment
clean-all:
	rm -rf src/vendor || true

# Performs sanity check on code
sanity-check: ## Perform code sanity checks if needed
	R -e 'devtools::spell_check()'

# Build the package source
build: build-wrappers build-vendor document-vendor document
	R -e 'devtools::build()'

# Vendor the rust sources
build-vendor:
  Rscript dev/vendoring.R

# Update wrappers
build-wrappers:
  Rscript -e 'savvy::savvy_update()'

# Generate documentation
document:
  R -e 'devtools::document()'

# Generate the AUTHORS file for rust crate vendor
document-vendor:
  Rscript dev/vendor-authors.R -m {{manifest}} -o ./inst --verbose
  Rscript dev/vendor-license-note.R
