# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_samplr_wrappers", use_symbols = TRUE, package_name = "samplr")

#' @usage NULL
#' @useDynLib samplr, .registration = TRUE
NULL

rust_unequal <- function(r_prob, r_eps, r_seed, r_method, r_max_iter) .Call(wrap__rust_unequal, r_prob, r_eps, r_seed, r_method, r_max_iter)

rust_unequal_conditional_poisson <- function(r_prob, r_sample_size, r_eps, r_seed, r_max_iter) .Call(wrap__rust_unequal_conditional_poisson, r_prob, r_sample_size, r_eps, r_seed, r_max_iter)

rust_spatially_balanced <- function(r_prob, r_data, r_eps, r_bucket_size, r_seed, r_method) .Call(wrap__rust_spatially_balanced, r_prob, r_data, r_eps, r_bucket_size, r_seed, r_method)

rust_balanced <- function(r_prob, r_bal_data, r_eps, r_seed, r_method) .Call(wrap__rust_balanced, r_prob, r_bal_data, r_eps, r_seed, r_method)

rust_doubly_balanced <- function(r_prob, r_data, r_bal_data, r_eps, r_bucket_size, r_seed, r_method) .Call(wrap__rust_doubly_balanced, r_prob, r_data, r_bal_data, r_eps, r_bucket_size, r_seed, r_method)

rust_spatially_balanced_hierarchical <- function(r_prob, r_data, r_sizes, r_eps, r_bucket_size, r_seed, r_method) .Call(wrap__rust_spatially_balanced_hierarchical, r_prob, r_data, r_sizes, r_eps, r_bucket_size, r_seed, r_method)

rust_balanced_stratified <- function(r_prob, r_bal_data, r_strata, r_eps, r_seed, r_method) .Call(wrap__rust_balanced_stratified, r_prob, r_bal_data, r_strata, r_eps, r_seed, r_method)

rust_doubly_balanced_stratified <- function(r_prob, r_data, r_bal_data, r_strata, r_eps, r_bucket_size, r_seed, r_method) .Call(wrap__rust_doubly_balanced_stratified, r_prob, r_data, r_bal_data, r_strata, r_eps, r_bucket_size, r_seed, r_method)

rust_local_mean_variance <- function(r_values, r_prob, r_data, r_neighbours) .Call(wrap__rust_local_mean_variance, r_values, r_prob, r_data, r_neighbours)

rust_spatial_balance_measure <- function(r_sample, r_prob, r_data, r_method) .Call(wrap__rust_spatial_balance_measure, r_sample, r_prob, r_data, r_method)

rust_balance_deviation <- function(r_sample, r_prob, r_data) .Call(wrap__rust_balance_deviation, r_sample, r_prob, r_data)

rust_pips_from_values <- function(r_values, r_sample_size) .Call(wrap__rust_pips_from_values, r_values, r_sample_size)


# nolint end
