# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_samplr_wrappers", use_symbols = TRUE, package_name = "samplr")

#' @usage NULL
#' @useDynLib samplr, .registration = TRUE
NULL

rust_lpm_2 <- function(r_prob, r_data, r_eps, r_bucket_size, r_seed) .Call(wrap__rust_lpm_2, r_prob, r_data, r_eps, r_bucket_size, r_seed)


# nolint end
