[package]
name = "envisim_samplr"
version = "0.5.0"
edition = "2024"
authors = ["Wilmer Prentius <wilmer.prentius@slu.se>"]
homepage = "https://envisim.se"
repository = "https://github.com/envisim/rust-samplr"
description = "Sampling methods for balanced and spatially balanced sampling"
keywords = ["sampling", "statistics"]
categories = ["mathematics", "science", "science::geo"]
license = "AGPL-3.0-only"
include = ["/src", "LICENSE", "README.md", "CHANGELOG.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
num-integer = "0.1.46"
num-traits = "0.2.19"
envisim_utils = {version="0.4.0", path="../envisim_utils", default-features=false}
rustc-hash = "2.1.1"

[dev-dependencies]
envisim_utils = {path="../envisim_utils", default-features=false, features=["rand", "test-utils"]}
