rust_src := 'src/rust'
manifest := rust_src + '/Cargo.toml'
cargo_lock := rust_src + '/Cargo.lock'
r_source := 'R/*'
rust_source := rust_src + '/src/**/*.rs'
build_path := 'build'

# Default to just --list
default:
  @just --list

# Clean the environment
clean-all:
	rm -rf src/vendor || true

# Performs sanity check on code
sanity-check: ## Perform code sanity checks if needed
	R -e 'devtools::spell_check("{{build_path}}")'

# Do a dev build
build-dev: build-wrappers document
    mkdir -p {{build_path}}
    R -e 'devtools::build(path = "{{build_path}}")'

# Build the package source
build: build-wrappers build-vendor document-vendor document
    mkdir -p {{build_path}}
    R -e 'devtools::build(path = "{{build_path}}")'
    R -e 'devtools::build_manual("{{build_path}}", "{{build_path}}")'

# Vendor the rust sources
build-vendor:
  Rscript dev/vendoring.R

# Update wrappers
build-wrappers:
  Rscript -e 'savvy::savvy_update()'

# Generate documentation
document:
  R -e 'devtools::document()'

# Generate the AUTHORS file for rust crate vendor
document-vendor:
  Rscript dev/vendor-authors.R -m {{manifest}} -o ./inst --verbose
  Rscript dev/vendor-license-note.R

# Check a build
check: build
    R -e 'devtools::check_built("{{build_path}}", cran = TRUE)'
